In [6]:
import numpy as np
import cv2

In [17]:
filename = "templates\static\pug.jpeg"

In [33]:
filename = "templates\static\pug.jpeg"

In [71]:
img = cv2.imread(filename, cv2.IMREAD_COLOR)

In [72]:
def histograma(img, bins):
    h, b = np.histogram(img, bins)
    return h

In [74]:
h = histograma(img, 255)

In [38]:
h

array([[   21,     2,     1,     2,     3,     2,     4,     7,     5,
            7,     6,     9,     6,     8,     7,     6,     8,     7,
           13,     8,     7,    20,     8,    14,    16,    14,    14,
           10,    15,    16,    17,    16,    20,    11,    22,    22,
           15,    21,    21,    16,    21,    14,    21,    21,    13,
           17,    15,    20,    15,    12,    20,    23,    17,     8,
           21,    22,    20,    17,    22,    15,    18,    24,    24,
           14,    19,    19,    14,    20,    15,    20,    20,    17,
           13,    10,    18,    13,    10,    16,    10,    12,    14,
           12,     8,    11,    16,    16,    10,    14,     6,    15,
            9,     8,    11,     8,    18,    16,    14,    12,     9,
           12,    14,    10,    14,    12,    16,    17,    10,    15,
           12,    13,     9,     8,    12,    16,    12,    11,    20,
            9,    10,     7,    15,     7,    10,    12,    14,     7,
      

In [24]:
def histograma2(img, bins):
    red, b = np.histogram(img[:,:,0], bins)
    green, b = np.histogram(img[:,:,1], bins)
    blue, b  = np.histogram(img[:,:,2], bins)
    h = np.array([red, green, blue])
    return h

In [42]:
h = histograma2(img)

In [29]:
h2 = h

In [39]:
d = np.sqrt(np.dot(h.T, h2))

In [41]:
sum(d)

array([ 12737.49119063,   4072.74101748,   3455.41890877,   4921.95107074,
         4970.37966829,   5657.15894036,   6404.3165372 ,   7579.51326117,
         6409.3175781 ,   6163.75393558,   7258.75679213,   9040.07357477,
         7823.22744583,   7358.01028206,   8304.8664926 ,   8318.822902  ,
         8597.16804214,   7333.06105903,   9783.36596186,   8995.99502012,
         8111.02687145,  12933.26018001,   9628.3168553 ,  11463.21832341,
        11492.85068038,  11589.9575086 ,  11589.9575086 ,  11454.20943684,
        11634.04083654,  12158.2316432 ,  12234.00493637,  12276.15089469,
        13994.29599523,  11726.04655005,  13599.14308279,  14147.01713044,
        12322.87357418,  14234.60915186,  14095.2041509 ,  13348.29382909,
        13990.66019869,  13839.27932728,  13727.42934008,  14694.48112436,
        13632.29985346,  14470.79299891,  14330.84515801,  14799.88777832,
        13084.48424386,  12901.8028418 ,  15664.04754737,  15074.09208268,
        14288.83755234,  

In [21]:
r, g, b = histograma2(img)

In [23]:
r

array([   21,     2,     1,     2,     3,     2,     4,     7,     5,
           7,     6,     9,     6,     8,     7,     6,     8,     7,
          13,     8,     7,    20,     8,    14,    16,    14,    14,
          10,    15,    16,    17,    16,    20,    11,    22,    22,
          15,    21,    21,    16,    21,    14,    21,    21,    13,
          17,    15,    20,    15,    12,    20,    23,    17,     8,
          21,    22,    20,    17,    22,    15,    18,    24,    24,
          14,    19,    19,    14,    20,    15,    20,    20,    17,
          13,    10,    18,    13,    10,    16,    10,    12,    14,
          12,     8,    11,    16,    16,    10,    14,     6,    15,
           9,     8,    11,     8,    18,    16,    14,    12,     9,
          12,    14,    10,    14,    12,    16,    17,    10,    15,
          12,    13,     9,     8,    12,    16,    12,    11,    20,
           9,    10,     7,    15,     7,    10,    12,    14,     7,
          13,    12,

In [51]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(4, 5, 6), (1, 2, 3)])

#np.sqrt(np.dot(a.T, a))

np.linalg.norm(a - b)

7.3484692283495345

In [52]:
a-b

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [4]:
def leer_img(filename):
    img = cv2.imread(filename, cv2.IMREAD_COLOR)
    return img

In [1]:
from distancia import euclidea
from caracteristicas import histograma_byn, histograma_rgb

In [2]:
filename1 = "templates\static\pug.jpeg"
filename2 = "templates\static\palmera.jpeg"

In [7]:
img1 = leer_img(filename1)
img2 = leer_img(filename2)

In [68]:
def histograma_byn2(img, bins):
    h, b = np.histogram(img, bins)
    return h

In [9]:
h1 = histograma_rgb(img1, 255)
h2 = histograma_rgb(img2, 255)

TypeError: 'NoneType' object is not subscriptable